d/tests/installed-tests: Assert that at least one test was run

diff --git a/debian/tests/installed-tests b/debian/tests/installed-tests
--- a/debian/tests/installed-tests
+++ b/debian/tests/installed-tests
@@ -2,6 +2,8 @@
 
 set -eu
 
+namespace=SDL2/
+
 if [ -z "${HOME-}" ] || ! [ -w "${HOME}" ]; then
     export HOME="${AUTOPKGTEST_TMP}"
 fi
@@ -10,4 +12,9 @@ export SDL_AUDIODRIVER=dummy
 export SDL_VIDEODRIVER=dummy
 cd "$AUTOPKGTEST_TMP"
 
-exec ginsttest-runner --tap SDL2
+if [ -z "$(ginsttest-runner -l "$namespace")" ]; then
+    echo "Error: no installed-tests found matching $namespace" >&2
+    exit 1
+fi
+
+exec ginsttest-runner --tap "$namespace"
